### ISSUE TITLE
help menu error 

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/PFEIFER#32]
I get an error everytime I start pfiefer.  

Undefined function or variable 'setHelpMenus'.

Error in PFEIFER (line 54)
setHelpMenus(workbenchFigObj)      % and set help buttons

osx 10.12
matlab 2017b

**Comment by jessdtate** [comment]
pfiefer still seems to work fine otherwise

**Comment by wgood** [comment]
This is the most up to date version of PFEIFER?

**Comment by bzenger** [comment]
You need to add the entire PFEIFER folder to the path, not just “source.”

**Comment by wgood** [comment]
Sorry Jess. The language in the README and the manual did not agree with each other. Both documents now say that you have to add the entire PFEIFER folder to the matlab path.
